### ISSUE TITLE
usbdrivedetector library returns empty value with the getRemovableDevices() function with MAC OS with JRE version 1.8.0_341-b10

### ISSUE THREAD

**Issue by vinodskukke** [samuelcampos/usbdrivedetector#44]
usbdrivedetector library is not detecting the USB drive(FAT32) in the MAC OS (Monterey) with the latest JRE update 1.8.0_341.
In fact Library sends the connected event but driveDetector.getRemovableDevices() returns empty value. I even tried to run the Application with sudo mode and still same issue persists. Can you please help me on this.

**Failure logs:**
[Thread-14] ERROR net.samuelcampos.usbdrivedetector.USBDeviceDetectorManager - An IUSBDriveListener threw an exception\
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0\
	net.samuelcampos.usbdrivedetector.USBDeviceDetectorManager.sendEventToListeners(USBDeviceDetectorManager.java:221)\
	at net.samuelcampos.usbdrivedetector.USBDeviceDetectorManager.lambda$updateConnectedDevices$0(USBDeviceDetectorManager.java:202)\
	at java.util.ArrayList.forEach(ArrayList.java:1259)\
	at net.samuelcampos.usbdrivedetector.USBDeviceDetectorManager.updateConnectedDevices(USBDeviceDetectorManager.java:201)\
	at net.samuelcampos.usbdrivedetector.USBDeviceDetectorManager.access$100(USBDeviceDetectorManager.java:32)\
	at net.samuelcampos.usbdrivedetector.USBDeviceDetectorManager$ListenerTask.run(USBDeviceDetectorManager.java:247)\

**Comment by weirdkid** [comment]
I'm seeing the same thing in macOS 13 (Ventura). Tried 2 different Java 1.8 JRE's: 1.8.301_09 and AdoptOpenJDK 1.8.0_292

Interestingly, the same code works in Java 11.

**Comment by weirdkid** [comment]
OK -- I figured it out. The OSXStorageDeviceDetector has a test in it where if the detected macos version is greater than 8 (Mountain Lion) it uses the df -l command instead of the system_profiler command. In java 8, the os version is correctly returned, but df -l must have changed in Monterey or earlier because the command no longer lists any removable devices. 

Now, it works in java 11 because the detected macos version number is actually returned incorrect as "0", but this forces the Detector to use the system_profiler code -- which still works.

So, an easy fix would be to remove the test for os version and the code that uses "df -l". When I do this, it works in Java 8. But -- I don't know if this will break older versions of macOS.

So the question for Samuel is why is the there 2 ways of getting the list of devices? Was the "ds -l" way added because it was faster or more reliable? Were there cases where system_profiler did not work?

**Comment by samuelcampos** [comment]
Just add the time today to pick this up.

The `df -l` alrernative was addes on this https://github.com/samuelcampos/usbdrivedetector/pull/11. You were the author.
I think that the reason to include it was due to the fact that `system_profiler` doesn't bring the "Mount Point" since macOs 10.8. The "Mount Point" is important for some use cases.

**Comment by HozakaN** [comment]
Hi. Could you publish a new version containing the fix for MacOs please ?
