### ISSUE TITLE
Crash on macos when a device connects

### ISSUE THREAD

**Issue by andretietz** [samuelcampos/usbdrivedetector#50]
I am using version 2.2.1 of `usbdrivedetector` on macOS(Sequoia 15.1.1). Same version on windows (11 Pro) works, with the same device connecting.

Connecting the device throws following exception:
```
09:41:11.154 [pool-2-thread-1] ERROR net.samuelcampos.usbdrivedetector.USBDeviceDetectorManager -- An IUSBDriveListener threw an exception
java.lang.NullPointerException: getUuid(...) must not be null
	at com.andretietz.audiopen.usbdetector.USBDetector$detect$1$listener$1.usbDriveEvent(USBDetector.kt:36)
	at net.samuelcampos.usbdrivedetector.USBDeviceDetectorManager.sendEventToListeners(USBDeviceDetectorManager.java:240)
	at net.samuelcampos.usbdrivedetector.USBDeviceDetectorManager.lambda$updateConnectedDevices$0(USBDeviceDetectorManager.java:221)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at net.samuelcampos.usbdrivedetector.USBDeviceDetectorManager.updateConnectedDevices(USBDeviceDetectorManager.java:220)
	at net.samuelcampos.usbdrivedetector.USBDeviceDetectorManager.access$200(USBDeviceDetectorManager.java:37)
	at net.samuelcampos.usbdrivedetector.USBDeviceDetectorManager$ListenerTask.run(USBDeviceDetectorManager.java:267)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Might this be a permission problem?

**Comment by andretietz** [comment]
I am using this in Kotlin (MP) and I am assuming, that the UUID is a non-nullable. 
Well, I shouldn't.
@samuelcampos 
Is there a chance we get a KMP version of this library?
